spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/surveyape
    username: root
    password: pass
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
